---
- hosts: vagrants
  sudo: true
  user: vagrant
  tasks:
    - name: install packages nginx
      yum: pkg={{ item }} state=installed
      with_items:
         - httpd
    - name: start httpd service
      service: name=httpd state=started enabled=yes

      